title: Workshop on Meta-Learning (MetaLearn 2017)
email: roberto.calandra@berkeley.edu
author: Roberto Calandra
description: "NIPS 2017 <br> Saturday 09 December 2017 <br> Hyatt Beacon Ballroom D+E+F+H"
baseurl: ""
url: "http://metalearning.ml"

theme: jekyll-theme-cayman

# Google services
google_analytics: UA-99852557-1
google_verification:

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
  auto_ids:       true
  
plugins_dir:
  - jekyll-seo-tag
  - jekyll-sitemap
