title: Workshop on Meta-Learning
email: roberto.calandra@berkeley.edu
author: Roberto Calandra
description: "NIPS 2017 <br> December 2017 <br> Long Beach Convention Center, Long Beach"
baseurl: ""
url: "http://metalearning.io"

theme: jekyll-theme-cayman

# Google services
google_analytics: UA-99852557-1
google_verification:

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
  auto_ids:       true
