title: Workshop on Meta-Learning (MetaLearn 2018)
email: roberto.calandra@berkeley.edu
author: Roberto Calandra
description: "@NIPS 2018 <br> Saturday 08 December 2018 <br> Palais des Congrès de Montréal, Montréal, Canada"
baseurl: ""
url: "http://metalearning.ml"

theme: jekyll-theme-cayman

# Google services
google_analytics: UA-99852557-1
google_verification:

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
  auto_ids:       true
  
plugins_dir:
  - jekyll-seo-tag
  - jekyll-sitemap
